version: 2
jobs:
  build:
    working_directory: ~/tsickle
    docker:
      - image: angular/ngcontainer:0.5.0
    steps:
      - checkout
      - restore_cache:
          key: tsickle-{{ checksum "yarn.lock" }}
      # Don't lock the bazel server, so that yarn can call bazel again
      - run: bazel run @nodejs//:yarn --script_path=yarn_install.sh && ./yarn_install.sh
      - run: bazel build ...
      - save_cache:
          key: tsickle-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
