/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * module namespace wrapper
 * @const
 */
var tsickle_module_externs$test_files_export_as_namespace_importeq_export_as_namespace_importeq = {};
/** @const */
tsickle_module_externs$test_files_export_as_namespace_importeq_export_as_namespace_importeq.anamespace = {};
/**
 * @constructor
 * @struct
 */
tsickle_module_externs$test_files_export_as_namespace_importeq_export_as_namespace_importeq.anamespace.NamespacedClass = function() {};

// export assignment handled via export as namespace

// export as namespace declaration handled at end of file
/** @const @suppress {duplicate} */
tsickle_module_externs$test_files_export_as_namespace_importeq_export_as_namespace_importeq.exportedNamespaceIncludingImportEq = {};
/** @const @suppress {duplicate} */
tsickle_module_externs$test_files_export_as_namespace_importeq_export_as_namespace_importeq.exportedNamespaceIncludingImportEq.NamespacedClass = tsickle_module_externs$test_files_export_as_namespace_importeq_export_as_namespace_importeq.anamespace.NamespacedClass;

