/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.

// NOTE: externs module has no export as namespace declaration.
// exported symbols other than augmentations of modules will
// not be visible to Closure Compiler.
/**
 * module namespace wrapper
 * @const
 */
var tsickle_module_externs$test_files_augment_angular_augment = {};

// TODO(tsickle): ImportDeclaration in tsickle_module_externs$test_files_augment_angular_augment
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "./angular"

/** @typedef {string} */
tsickle_declare_module.__angular.sub.AugmentSubType;
/** @const */
tsickle_declare_module.__angular.local = {};

/** @typedef {string} */
tsickle_declare_module.__angular.local.LocalType;

/** @typedef {!angular.IFooBar} */
tsickle_declare_module.__angular.local.UsingSymbolFromAugmentedModule;
/**
 * module namespace wrapper
 * @const
 */
var tsickle_module_externs$test_files_augment_angular_index = {};

// export assignment handled via export as namespace

// export as namespace declaration handled at end of file
 /** @type {string} */
tsickle_module_externs$test_files_augment_angular_index.angular;
/**
 * @record
 * @struct
 */
tsickle_module_externs$test_files_augment_angular_index.angular.IFooBar = function() {};
 /** @type {string} */
tsickle_module_externs$test_files_augment_angular_index.angular.IFooBar.prototype.field;
/** @const */
tsickle_module_externs$test_files_augment_angular_index.angular.sub = {};

/** @typedef {string} */
tsickle_module_externs$test_files_augment_angular_index.angular.sub.SubType;
/** @const @suppress {duplicate} */
tsickle_module_externs$test_files_augment_angular_index.angular = {};
/** @const @suppress {duplicate} */
tsickle_module_externs$test_files_augment_angular_index.angular.IFooBar = tsickle_module_externs$test_files_augment_angular_index.angular.IFooBar;

/** @const @suppress {duplicate} */
tsickle_module_externs$test_files_augment_angular_index.angular.sub = tsickle_module_externs$test_files_augment_angular_index.angular.sub;

/** @const @suppress {duplicate} */
tsickle_module_externs$test_files_augment_angular_index.angular.local = tsickle_module_externs$test_files_augment_angular_index.local;

